### ISSUE TITLE
在arm架构下编译失败

### ISSUE THREAD

**Issue by dingleshu** [CuteReimu/TheMessage#194]
pi@raspberrypi:~/Documents/TheMessage $ ./gradlew build
Downloading https://services.gradle.org/distributions/gradle-8.7-bin.zip
............10%.............20%.............30%.............40%............50%.............60%.............70%.............80%.............90%............100%

Welcome to Gradle 8.7!

Here are the highlights of this release:
 - Compiling and testing with Java 22
 - Cacheable Groovy script compilation
 - New methods in lazy collection properties

For more details see https://docs.gradle.org/8.7/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)
> Task :generateProto FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateProto'.
> Could not resolve all files for configuration ':protobufToolsLocator_protoc'.
   > Could not find protoc-4.26.0-linux-aarch_64.exe (com.google.protobuf:protoc:4.26.0).
     Searched in the following locations:
         https://maven.aliyun.com/repository/public/com/google/protobuf/protoc/4.26.0/protoc-4.26.0-linux-aarch_64.exe

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 4m 52s
4 actionable tasks: 4 executed

**Comment by CuteReimu** [comment]
从阿里云的镜像没拉到 https://maven.aliyun.com/repository/public/com/google/protobuf/protoc/4.26.0/protoc-4.26.0-linux-aarch_64.exe
阿里云抽了吧，把 build.gradle.kts 里面阿里云镜像删了，只从maven中心拉就行了

**Comment by dingleshu** [comment]
更换腾讯云的镜像即可：https://mirrors.cloud.tencent.com/nexus/repository/maven-public/
