### ISSUE TITLE
在选角色时退出再进来，选不了角色了

### ISSUE THREAD

**Issue by CuteReimu** [CuteReimu/TheMessage#222]
- 出现这个问题时，并不是打开客户端后的第一局。
- 在大厅切后台了，然后游戏开始了，于是就出现这个问题了。
- 在选角色时退出再进来，也会出现这个问题。
- 出现这个问题后，退出再进，仍然没好。
- 出现这个问题后，重启客户端，仍然没好。
- 出现这个问题后，选角色超时后，能正常开始游戏。

**Comment by CuteReimu** [comment]
客户端bug

**Comment by CuteReimu** [comment]
@Death-alter 没修好

**Comment by Death-alter** [comment]
测试未发现问题

**Comment by CuteReimu** [comment]
@Death-alter 还没修好
